package br.com.stdy_soap.courses;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.3.2
 * 2019-07-15T21:58:26.005-03:00
 * Generated source version: 3.3.2
 *
 */
@WebService(targetNamespace = "http://stdy-soap.com.br/courses", name = "CoursePort")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface CoursePort {

    @WebMethod(operationName = "GetAllCourseDetails")
    @WebResult(name = "GetAllCourseDetailsResponse", targetNamespace = "http://stdy-soap.com.br/courses", partName = "GetAllCourseDetailsResponse")
    public GetAllCourseDetailsResponse getAllCourseDetails(

        @WebParam(partName = "GetAllCourseDetailsRequest", name = "GetAllCourseDetailsRequest", targetNamespace = "http://stdy-soap.com.br/courses")
        GetAllCourseDetailsRequest getAllCourseDetailsRequest
    );

    @WebMethod(operationName = "GetCourseDetails")
    @WebResult(name = "GetCourseDetailsResponse", targetNamespace = "http://stdy-soap.com.br/courses", partName = "GetCourseDetailsResponse")
    public GetCourseDetailsResponse getCourseDetails( 
    		@WebParam(partName = "GetCourseDetailsRequest", name = "GetCourseDetailsRequest", targetNamespace = "http://stdy-soap.com.br/courses")
        GetCourseDetailsRequest getCourseDetailsRequest 
    );
}
